name: Refresh Vercel
on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: |
          curl -X GET "https://github-readme-stats-jwu910.vercel.app/api/top-langs/?username=jwu910&layout=compact&theme=onedark&langs_count=6&custom_title=Top%20Languages&card_width=265&hide=java#gh-dark-mode-only"
