name: Refresh Vercel
on:
  workflow_dispatch:
  schedule:
    - cron: "*/120 * * * *"
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping
        run: |
          curl -X GET "https://github-readme-stats-jwu910.vercel.app/api/top-langs/?username=jwu910&layout=compact&theme=onedark&langs_count=6&custom_title=Top%20Languages&card_width=265&hide=java"
          curl -X GET "https://github-readme-stats-jwu910.vercel.app/api?username=jwu910&show_icons=true&hide=issues&theme=default&line_height=24&border_radius=5"
